name: Hello Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  hello:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Echo hello
        run: |
          echo hello
          exit 1
